<a href="https://colab.research.google.com/github/hifsakazmi/assignment_alpha/blob/main/Question_6_Single_Head_and_Multihead_Attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Single Head Attention

Complete the pseudo-code





In [6]:
import numpy as np

In [7]:
def softmax(scores, axis=-1):
  scores = scores - scores.max(axis=axis, keepdims=True)
  return np.exp(scores) / np.exp(scores).sum(axis=axis, keepdims=True)

def scaled_dot_product_attention(Q, K, V, mask = None):
  # Q: (T_q × d_k), K: (T_k × d_k), V: (T_k × d_v) where typically d_k = d_v
  # mask: optional, shape (T_q × T_k), with e.g. -∞ entries for masked positions

  scores = np.dot(Q, K.T)

  # Scale by d_k
  d_k = K.shape[1]
  scores = scores / np.sqrt(d_k)

  # Apply mask
  if mask is not None:
    scores = scores + mask # mask has -inf or large negative values

  # Apply softmax on QKt
  attention_weights = softmax(scores, axis=-1)
  output = attention_weights @ V
  return output, attention_weights


### Test with data from Question 4

Sentence: Agentic AI new course

In [8]:
  Q = np.array([[1, 3],
      [2, 4],
      [2, 4.4],
      [2.4, 4]])

  K = np.array([[1, 2],
      [1, 3],
      [1, 3],
      [1, 3]])

  V = np.array([[0.2, 0.3],
      [2, 0.3],
      [2.2, 0.3],
      [2.2, 0.3]])

output, weights = scaled_dot_product_attention(Q, K, V)

print("Attention Weights:")
print(weights)
print("Output")
print(output)

Attention Weights:
[[0.03842247 0.32052584 0.32052584 0.32052584]
 [0.01932125 0.32689292 0.32689292 0.32689292]
 [0.01463088 0.32845637 0.32845637 0.32845637]
 [0.01932125 0.32689292 0.32689292 0.32689292]]
Output
[[2.05904988 0.3       ]
 [2.09597892 0.3       ]
 [2.10504697 0.3       ]
 [2.09597892 0.3       ]]


# Multihead Attention

In [10]:
def multihead_attention(Q, K, V, h):
    d_model = Q.shape[1]
    d_k = d_model // h

    heads = []
    for i in range(h):
      # Randomly initialize W_Q, W_K, W_V
      W_Q = np.random.randn(d_model, d_k)
      W_K = np.random.randn(d_model, d_k)
      W_V = np.random.randn(d_model, d_k)

      weighted_Q = np.matmul(Q, W_Q)
      weighted_K = np.matmul(K, W_K)
      weighted_V = np.matmul(V, W_V)
      # Run scaled dot product attention
      output, _ = scaled_dot_product_attention(weighted_Q, weighted_K, weighted_V)

      heads.append(output)

    # concatenate all heads
    multi_head_output = np.concatenate(heads, axis=1)

    # Apply weights to multihead output
    W_O = np.random.randn(d_model, d_model)
    output = np.matmul(multi_head_output, W_O)
    return output